SET NOCOUNT ON
SET ANSI_WARNINGS OFF
:setvar SQLCMDERRORLEVEL 1
GO

USE tempdb
DROP DATABASE IF EXISTS DXStatisticsV2
DROP DATABASE IF EXISTS scpaid_audit
DROP DATABASE IF EXISTS SupportCenterPaid
GO

PRINT 'test db: down'
