version: '3.4'

x-support_analytics_service:
  &support_analytics_service
  build:
    context: .
    dockerfile: Dockerfile

services:

  support_analytics_worker:
    <<: *support_analytics_service

  support_analytics_dashboard:
    <<: *support_analytics_service

  support_analytics_server:
    <<: *support_analytics_service
