version: '3.4'

x-support_analytics_service:
  &support_analytics_service
  image: shchelokovskiy/support_analytics_service:latest
  restart: always
  environment:
    - SQL_SERVER
    - SQL_DATABASE
    - SQL_USER
    - SQL_PASSWORD
    - SERVER_PORT
    - FLOWER_PORT
    - CORS_ORIGINS
    - QUERY_SERVICE
    - REDIS_SERVICE
    - REDIS_PORT
    - CELERY_BROKER_URL=redis://${REDIS_SERVICE}:${REDIS_PORT}/1
    - CELERY_RESULT_BACKEND=redis://${REDIS_SERVICE}:${REDIS_PORT}/1
    - REDIS_DB=SUPPORT_ANALYTICS
    - DB_HOME
    - SQLITE_DATABASE=${DB_HOME}/db

services:
  support_analytics_worker:
    <<: *support_analytics_service
    hostname: support_analytics_worker
    container_name: support_analytics_worker
    command: celery --app worker worker --beat --loglevel=INFO --concurrency 7 #--logfile=logs/celery.log
    volumes:
      - support_analytics-volume:${DB_HOME}

  support_analytics_dashboard:
    <<: *support_analytics_service
    hostname: support_analytics_dashboard
    container_name: support_analytics_dashboard
    command: celery -A worker flower --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - support_analytics_worker

  support_analytics_server:
    <<: *support_analytics_service
    hostname: support_analytics_server
    container_name: support_analytics_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: uvicorn server:app --host 0.0.0.0 --port $SERVER_PORT
    volumes:
      - support_analytics-volume:${DB_HOME}

networks:
  default:
    name: support_analytics
    external: true

volumes:
  support_analytics-volume:
