version: '3.4'

x-support_analytics_service:
  &support_analytics_service
  image: shchelokovskiy/support_analytics_service:latest
  restart: always
  environment:
    - SQL_SERVER
    - SQL_DATABASE
    - SQL_USER
    - SQL_PASSWORD
    - CELERY_BROKER_URL
    - CELERY_RESULT_BACKEND
    - SQLITE_DATABASE
    - USER_POSTS_SQL
    - USER_POSTS_TABLE_NAME
    - SERVER_PORT

services:
  support_analytics_worker:
    <<: *support_analytics_service
    hostname: support_analytics_worker
    container_name: support_analytics_worker
    command: celery --app user_posts_worker worker --beat --loglevel=INFO --concurrency 7 #--logfile=logs/celery.log
    volumes:
      - support_analytics-volume:${DB_HOME}

  support_analytics_dashboard:
    <<: *support_analytics_service
    hostname: support_analytics_dashboard
    container_name: support_analytics_dashboard
    command: celery -A user_posts_worker flower --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - support_analytics_worker

  support_analytics_server:
    <<: *support_analytics_service
    hostname: support_analytics_server
    container_name: support_analytics_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: uvicorn support_analytics_server:app --host 0.0.0.0 --port $SERVER_PORT

networks:
  default:
    name: support_analytics
    external: true

volumes:
  support_analytics-volume:
