version: '3.4'

x-user_posts_statistic_service:
  &user_posts_statistic_service
  image: shchelokovskiy/user_posts_statistic_worker_service:latest
  restart: always
  environment:
    - SQL_SERVER
    - SQL_DATABASE
    - SQL_USER
    - SQL_PASSWORD
    - APP_SERVER_PORT
    - CELERY_BROKER_URL
    - CELERY_RESULT_BACKEND
    - SQLITE_DATABASE
    - CLIENT_POSTS_SQL

services:

  # application_server:
  #   image: shchelokovskiy/application_server:latest
  #   restart: always
  #   hostname: application_server
  #   container_name: application_server
  #   environment:
  #     - APP_SERVER_PORT
  #     - REDIS_SERVICE=redis_service
  #     - FORECASTER_DB
  #     - USERS_STATISTIC_DB
  #   ports:
  #     - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"

  user_posts_statistic_worker_service:
    <<: *user_posts_statistic_service
    hostname: user_posts_statistic_worker_service
    container_name: user_posts_statistic_worker_service
    command: celery --app user_posts_worker worker --beat --loglevel=INFO --concurrency 7 #--logfile=logs/celery.log
    volumes:
      - db:${DB_HOME}

  user_posts_statistic_dashboard:
    <<: *user_posts_statistic_service
    hostname: user_posts_statistic_dashboard
    container_name: user_posts_statistic_dashboard
    command:  celery -A user_posts_worker flower --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - user_posts_statistic_worker_service

volumes:
  db:

networks:
  default:
    name: support_analytics
    external: true