version: '3.4'

x-user_posts_statistic_service:
    &user_posts_statistic_service
    build:
      context: user_posts_statistic_service
      dockerfile: Dockerfile.user_posts_statistic_service

services:

  user_posts_statistic_worker_service:
    <<: *user_posts_statistic_service

  # application_server:
  #   build:
  #     context: application_server
  #     dockerfile: Dockerfile
