version: '3.4'

x-user_posts_statistic_service:
  &user_posts_statistic_service
  image: shchelokovskiy/user_posts_statistic_service:latest
  restart: always
  environment:
    - SQL_SERVER
    - SQL_DATABASE
    - SQL_USER
    - SQL_PASSWORD
    - CELERY_BROKER_URL
    - CELERY_RESULT_BACKEND
    - SQLITE_DATABASE
    - USER_POSTS_SQL
    - USER_POSTS_TABLE_NAME

services:

  user_posts_statistic_client:
    image: shchelokovskiy/user_posts_statistic_client:latest
    restart: always
    hostname: user_posts_statistic_client
    container_name: user_posts_statistic_client
    command: gunicorn -w 2 -t 120 -b 0.0.0.0:$APP_SERVER_PORT plotly_server:server
    environment:
      - SQLITE_DATABASE
      - USER_POSTS_TABLE_NAME
    volumes:
      - user-posts-volume:${DB_HOME}
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"

  user_posts_statistic_worker_service:
    <<: *user_posts_statistic_service
    hostname: user_posts_statistic_worker_service
    container_name: user_posts_statistic_worker_service
    command: celery --app user_posts_worker worker --beat --loglevel=INFO --concurrency 7 #--logfile=logs/celery.log
    volumes:
      - user-posts-volume:${DB_HOME}

  user_posts_statistic_dashboard:
    <<: *user_posts_statistic_service
    hostname: user_posts_statistic_dashboard
    container_name: user_posts_statistic_dashboard
    command:  celery -A user_posts_worker flower --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - user_posts_statistic_worker_service

networks:
  default:
    name: support_analytics
    external: true

volumes:
  user-posts-volume: