[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Stanislav Shchelokovskiy <stanislav.shchelokovskiy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.1"
pandas = "^1.4.3"
SQLAlchemy = "^1.4.39"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
yapf = "^0.32.0"
flake8 = "^4.0.1"
pylint = "^2.13.7"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-xdist = {extras = ["psutil"], version = "^2.5.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
