SET NOCOUNT ON
SET ANSI_WARNINGS OFF
:setvar SQLCMDERRORLEVEL 1
GO

USE tempdb
DROP DATABASE IF EXISTS CRM
DROP DATABASE IF EXISTS CRMAudit
DROP DATABASE IF EXISTS DXStatisticsV2
DROP DATABASE IF EXISTS SupportCenterPaid
DROP DATABASE IF EXISTS scpaid_audit
GO

PRINT 'test db: down'
