import toolbox.sql.generators.sqlite.statements as sqlite_index
from sql_queries.meta import (
    CATComponentsFeaturesMeta,
    BaselineAlignedCustomersGroupsMeta,
    EmployeesIterationsMeta,
    PlatformsProductsMeta,
    TicketsWithPropertiesMeta,
    TicketsWithIterationsMeta,
    CSIMeta,
)
import sql_queries.index.name as name_index


# yapf: disable
def get_create_index_statements() -> dict[str, tuple[str]]:
    return __create_index_statements

__create_index_statements = {
    name_index.tickets_with_iterations:
        (
            sqlite_index.generate_create_index_statement(
                tbl=name_index.tickets_with_iterations,
                cols=(
                    TicketsWithIterationsMeta.user_crmid,
                    TicketsWithIterationsMeta.ticket_scid,
                    TicketsWithIterationsMeta.creation_date,
                    TicketsWithIterationsMeta.ticket_type,
                    TicketsWithIterationsMeta.license_status,
                    TicketsWithIterationsMeta.emp_position_id,
                    TicketsWithIterationsMeta.is_private,
                    TicketsWithIterationsMeta.tribes_ids,
                    TicketsWithIterationsMeta.tent_id,
                ),
                name='tickets_inner',
            ),
            sqlite_index.generate_create_index_statement(
                tbl=name_index.tickets_with_iterations,
                cols=(
                    TicketsWithIterationsMeta.user_crmid,
                    TicketsWithIterationsMeta.emp_post_id,
                    TicketsWithIterationsMeta.creation_date,
                    TicketsWithIterationsMeta.ticket_type,
                    TicketsWithIterationsMeta.license_status,
                    TicketsWithIterationsMeta.emp_position_id,
                    TicketsWithIterationsMeta.is_private,
                    TicketsWithIterationsMeta.tribes_ids,
                    TicketsWithIterationsMeta.tent_id,
                ),
                name='iterations_inner',
            ),
            sqlite_index.generate_create_index_statement(
                tbl=name_index.tickets_with_iterations,
                cols=(
                    TicketsWithIterationsMeta.user_crmid,
                    TicketsWithIterationsMeta.creation_date,
                    TicketsWithIterationsMeta.ticket_type,
                    TicketsWithIterationsMeta.license_status,
                    TicketsWithIterationsMeta.emp_position_id,
                    TicketsWithIterationsMeta.is_private,
                    TicketsWithIterationsMeta.tribes_ids,
                    TicketsWithIterationsMeta.tent_id,
                    TicketsWithIterationsMeta.user_id,
                    TicketsWithIterationsMeta.ticket_scid,
                    TicketsWithIterationsMeta.emp_post_id,
                ),
                name='outer',
            ),
        ),
        name_index.customers_tickets:
            (
               sqlite_index.generate_create_index_statement(
                    tbl=name_index.customers_tickets,
                    cols=(
                        TicketsWithPropertiesMeta.user_crmid,
                        TicketsWithPropertiesMeta.creation_date,
                    )
                ),
            ),
        name_index.employees_iterations:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.employees_iterations,
                    cols=(EmployeesIterationsMeta.ticket_id,)
                ),
            ),
        name_index.cat_components_features:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.tent_id,
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.component_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.tent_id,
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.feature_id,
                        CATComponentsFeaturesMeta.feature_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.component_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.feature_id,
                        CATComponentsFeaturesMeta.feature_name,
                    )
                ),
            ),
        name_index.platforms_products:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.platforms_products,
                    cols=(
                        PlatformsProductsMeta.product_tent_id,
                        PlatformsProductsMeta.product_id,
                        PlatformsProductsMeta.product_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.platforms_products,
                    cols=(
                        PlatformsProductsMeta.platform_tent_id,
                        PlatformsProductsMeta.platform_id,
                        PlatformsProductsMeta.platform_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.platforms_products,
                    cols=(
                        PlatformsProductsMeta.platform_id,
                        PlatformsProductsMeta.platform_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.platforms_products,
                    cols=(
                        PlatformsProductsMeta.product_id,
                        PlatformsProductsMeta.product_name,
                    )
                ),
            ),
        name_index.tracked_customers_groups:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.assignment_date,
                        BaselineAlignedCustomersGroupsMeta.id,
                        BaselineAlignedCustomersGroupsMeta.user_crmid,
                        BaselineAlignedCustomersGroupsMeta.removal_date,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.user_crmid,
                        BaselineAlignedCustomersGroupsMeta.assignment_date,
                        BaselineAlignedCustomersGroupsMeta.id,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=name_index.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.id,
                        BaselineAlignedCustomersGroupsMeta.name,
                    )
                ),
            ),
        name_index.csi:
        (
            sqlite_index.generate_create_index_statement(
                    tbl=name_index.csi,
                    cols=(
                        CSIMeta.ticket_scid,
                        CSIMeta.date,
                        CSIMeta.rating,
                    )
                ),
        )
    }
