import toolbox.sql.generators.sqlite.index as sqlite_index
from sql_queries.meta import (
    CATComponentsFeaturesMeta,
    BaselineAlignedCustomersGroupsMeta,
    EmployeesIterationsMeta,
    PlatformsProductsMeta,
    TicketsWithPropertiesMeta,
    CSIMeta,
)
import sql_queries.index.db as DbIndex


# yapf: disable
def get_create_index_statements() -> dict[str, tuple[str]]:
    return __create_index_statements

__create_index_statements = {
        DbIndex.customers_tickets:
            (
               sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.customers_tickets,
                    cols=(
                        TicketsWithPropertiesMeta.user_crmid,
                        TicketsWithPropertiesMeta.creation_date,
                    )
                ),
            ),
        DbIndex.employees_iterations:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.employees_iterations,
                    cols=(EmployeesIterationsMeta.ticket_id,)
                ),
            ),
        DbIndex.cat_components_features:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.tent_id,
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.component_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.tent_id,
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.feature_id,
                        CATComponentsFeaturesMeta.feature_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.component_id,
                        CATComponentsFeaturesMeta.component_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.cat_components_features,
                    cols=(
                        CATComponentsFeaturesMeta.feature_id,
                        CATComponentsFeaturesMeta.feature_name,
                    )
                ),
            ),
        DbIndex.platforms_products:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.platforms_products,
                    cols=(
                        PlatformsProductsMeta.product_tent_id,
                        PlatformsProductsMeta.product_id,
                        PlatformsProductsMeta.product_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.platforms_products,
                    cols=(
                        PlatformsProductsMeta.platform_tent_id,
                        PlatformsProductsMeta.platform_id,
                        PlatformsProductsMeta.platform_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.platforms_products,
                    cols=(
                        PlatformsProductsMeta.platform_id,
                        PlatformsProductsMeta.platform_name,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.platforms_products,
                    cols=(
                        PlatformsProductsMeta.product_id,
                        PlatformsProductsMeta.product_name,
                    )
                ),
            ),
        DbIndex.tracked_customers_groups:
            (
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.assignment_date,
                        BaselineAlignedCustomersGroupsMeta.id,
                        BaselineAlignedCustomersGroupsMeta.user_crmid,
                        BaselineAlignedCustomersGroupsMeta.removal_date,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.user_crmid,
                        BaselineAlignedCustomersGroupsMeta.assignment_date,
                        BaselineAlignedCustomersGroupsMeta.id,
                    )
                ),
                sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.tracked_customers_groups,
                    cols=(
                        BaselineAlignedCustomersGroupsMeta.id,
                        BaselineAlignedCustomersGroupsMeta.name,
                    )
                ),
            ),
        DbIndex.csi:
        (
            sqlite_index.generate_create_index_statement(
                    tbl=DbIndex.csi,
                    cols=(
                        CSIMeta.ticket_scid,
                        CSIMeta.date,
                        CSIMeta.rating,
                    )
                ),
        )
    }
