import toolbox.sql.index as RootPath


extract_path = RootPath.get_cwd() + '/extract'
customers_groups = extract_path + '/groups.sql'
tracked_customers_groups = extract_path + '/tracked_groups.sql'
ticket_tags = extract_path + '/tags.sql'
tickets_types = extract_path + '/tickets_types.sql'
replies_types = extract_path + '/replies_types.sql'
frameworks = extract_path + '/frameworks.sql'
operating_systems = extract_path + '/operating_systems.sql'
builds = extract_path + '/builds.sql'
severity = extract_path + '/severity.sql'
ides = extract_path + '/ides.sql'
ticket_statuses = extract_path + '/ticket_statuses.sql'
components_features = extract_path + '/components_features.sql'
platforms_products = extract_path + '/platforms_products.sql'
employees = extract_path + '/employees.sql'
employees_iterations = extract_path + '/employees_iterations.sql'
tickets_with_licenses_and_users = extract_path + '/tickets_with_licenses_and_users.sql'
tickets_with_properties = extract_path + '/tickets_with_properties.sql'
