import toolbox.sql.index as RootPath


remote_path = RootPath.get_cwd() + '/remote'
customers_groups = remote_path + '/groups.sql'
tracked_customers_groups = remote_path + '/tracked_groups.sql'
ticket_tags = remote_path + '/tags.sql'
tickets_types = remote_path + '/tickets_types.sql'
replies_types = remote_path + '/replies_types.sql'
frameworks = remote_path + '/frameworks.sql'
operating_systems = remote_path + '/operating_systems.sql'
builds = remote_path + '/builds.sql'
severity = remote_path + '/severity.sql'
ides = remote_path + '/ides.sql'
ticket_statuses = remote_path + '/ticket_statuses.sql'
components_features = remote_path + '/components_features.sql'
platforms_products = remote_path + '/platforms_products.sql'
employees_iterations = remote_path + '/employees_iterations.sql'
employees = remote_path + '/employees.sql'
roles = remote_path + '/roles.sql'
tickets_with_licenses_and_users = remote_path + '/tickets_with_licenses_and_users.sql'
tickets_with_properties = remote_path + '/tickets_with_properties.sql'
tents = remote_path + '/tents.sql'
tribes = remote_path + '/tribes.sql'

metrics = remote_path + '/metrics'
csi = metrics + '/csi.sql'
resolution_time = metrics + '/resolution_time.sql'
