SET NOCOUNT ON
SET ANSI_WARNINGS OFF
:setvar SQLCMDERRORLEVEL 1
GO

CREATE DATABASE SupportCenterPaid
GO
CREATE DATABASE DXStatisticsV2
GO

USE SupportCenterPaid
GO

CREATE SCHEMA [c1f0951c-3885-44cf-accb-1a390f34c342]
GO

CREATE TABLE [c1f0951c-3885-44cf-accb-1a390f34c342].Tickets (
	Id			UNIQUEIDENTIFIER,
	FriendlyId	VARCHAR(20)
)

USE DXStatisticsV2
GO

CREATE TABLE FeedbackItems (
	TicketId	UNIQUEIDENTIFIER,
	RatingValue	INT,
	DateTime	DATETIME
)
