name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push user_posts_statistic_service
        uses: docker/build-push-action@v3
        with:
          context: user_posts_statistic_service
          file: user_posts_statistic_service/Dockerfile.user_posts_statistic_service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user_posts_statistic_worker_service:latest
      # - name: Build and Push application_server
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: application_server
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/application_server:latest
