name: Test
on:
  push:
    branches:
      - rc
      - release

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.11]
        poetry-version: [1.6.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: eRvLhAL104eRvLhAL104
        ports:
          - 1433:1433

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        shell: bash
        run: |
          poetry install
          sudo apt-get update
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/debian/11/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          ACCEPT_EULA=Y sudo apt-get install -y --no-install-recommends msodbcsql18 mssql-tools18 unixodbc-dev
      - name: Test
        run: poetry run pytest -xvs --disable-warnings
        env:
          SQL_SERVER: localhost:1433
          SQL_SERVER_SQLCMD: localhost,1433
          SQL_DATABASE: tempdb
          SQL_USER: sa
          SQL_PASSWORD: eRvLhAL104eRvLhAL104
          PRODUCTION: 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    concurrency: ${{ github.ref_name }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:${{ secrets.DOCKER_HUB_TAG }}
